<a href="https://colab.research.google.com/github/tom-d-c/sports-analytics/blob/dev-f1/MaxVSrest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

def to_seconds(time_str):
    minutes, seconds = map(float, time_str.split(':'))
    return minutes * 60 + seconds

data = [
    {'Name': 'Gasly', 'Time': to_seconds('1:23.020'), 'Time_Max': to_seconds('1:22.876')},
    {'Name': 'Gasly', 'Time': to_seconds('1:29.900'), 'Time_Max': to_seconds('1:29.579')},
    {'Name': 'Albon', 'Time': to_seconds('1:45.528'), 'Time_Max': to_seconds('1:44.622')},
    {'Name': 'Albon', 'Time': to_seconds('1:39.106'), 'Time_Max': to_seconds('1:38.540')},
    {'Name': 'Perez', 'Time': to_seconds('1:31.165'), 'Time_Max': to_seconds('1:30.499')},
    {'Name': 'Perez', 'Time': to_seconds('1:15.395'), 'Time_Max': to_seconds('1:15.109')},
    {'Name': 'Lawson', 'Time': to_seconds('1:17.094'), 'Time_Max': to_seconds('1:16.018')},
    {'Name': 'Lawson', 'Time': to_seconds('1:32.174'), 'Time_Max': to_seconds('1:31.424')},
]

df = pd.DataFrame(data)
df

     Name     Time  Time_Max
0   Gasly   83.020    82.876
1   Gasly   89.900    89.579
2   Albon  105.528   104.622
3   Albon   99.106    98.540
4   Perez   91.165    90.499
5   Perez   75.395    75.109
6  Lawson   77.094    76.018
7  Lawson   92.174    91.424

In [3]:
# Calculate the percentage difference between 'Time' and 'Time_Max'
df['Percentage_Difference'] = ((df['Time'] - df['Time_Max']) / df['Time_Max']) * 100

# Group by 'Name' and calculate the average percentage difference
average_percentage_difference = df.groupby('Name')['Percentage_Difference'].mean()

# Group by 'Name' and calculate the standard deviation of the percentage difference
std_percentage_difference = df.groupby('Name')['Percentage_Difference'].std()

# Combine average and standard deviation into a single DataFrame
result = pd.DataFrame({'Average_Percentage_Difference': average_percentage_difference,
                       'Std_Percentage_Difference': std_percentage_difference})

result

        Average_Percentage_Difference  Std_Percentage_Difference
Name
Albon                        0.720180                   0.206184
Gasly                        0.266048                   0.130524
Lawson                       1.117904                   0.420800
Perez                        0.558350                   0.251122

In [4]:
import plotly.graph_objects as go

# Create a list of names in the desired order
names = ['Gasly', 'Albon', 'Perez', 'Lawson']

# Create a list of colors
colors = ['slateblue'] * 3 + ['darkblue']

fig = go.Figure()
W = 1200
H = 600
for name, color in zip(names, colors):
    if name in result.index:
        average_diff = result.loc[name, 'Average_Percentage_Difference']
        std_diff = result.loc[name, 'Std_Percentage_Difference']

        fig.add_trace(go.Bar(
            x=[name],
            y=[average_diff],
            name=name,
            error_y=dict(type='data', array=[std_diff], color='black'),
            marker_color=color
        ))


fig.update_layout(
    title='How RedBull teammates compare to Verstappen in their first two qualifying sessions',
    title_x=0.5,  # Center the title
    yaxis_title='Q1 Gap to Verstappen (%)',
    barmode='group',  # Group the bars for better visualization
    showlegend=False,
    plot_bgcolor='white',
    width=W,
    height=H
)

fig.update_yaxes(range=[0, 1.6], dtick=0.5)
fig.update_xaxes(showline=True, linewidth=.5, linecolor='black')
fig.update_yaxes(showline=True, linewidth=.5, linecolor='black', ticks='outside')

fig.show()